# Generated by Django 4.2.1 on 2023-06-10 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='price',
            field=models.CharField(default=0, max_length=15),
        ),
        migrations.AddField(
            model_name='software',
            name='validity',
            field=models.CharField(choices=[('yearly', 'Yearly'), ('lifetime', 'Lifetime')], default='Lifetime', max_length=50),
        ),
        migrations.AddField(
            model_name='software',
            name='vendor',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AddField(
            model_name='software',
            name='version',
            field=models.CharField(default='NA', max_length=50),
        ),
    ]
