# Generated by Django 4.2.1 on 2023-06-15 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0008_rename_buy_date_hardware_buy_date'),
        ('software', '0002_software_price_software_validity_software_vendor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='Software',
            field=models.ManyToManyField(to='hardware.hardware'),
        ),
    ]
