# Generated by Django 4.2.1 on 2023-06-15 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_remove_location_id_alter_location_location_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='location_name',
            field=models.CharField(max_length=50),
        ),
    ]
