# Generated by Django 4.2.1 on 2023-06-15 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_location_id_alter_location_location_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='id',
        ),
        migrations.AlterField(
            model_name='location',
            name='location_name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
