# Generated by Django 4.2.1 on 2023-06-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Asset_ID', models.CharField(max_length=50)),
                ('Hardware_Name', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=50)),
                ('Price', models.CharField(max_length=15)),
            ],
        ),
    ]
