# Generated by Django 4.2.1 on 2023-06-06 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0001_initial'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='hardware',
        #     name='Buy_Date',
        #     field=models.DateField,
        # ),
        migrations.AddField(
            model_name='hardware',
            name='allotment',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='hardware',
            name='softwares',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='hardware',
            name='status',
            field=models.CharField(default='inactive', max_length=50),
        ),
        migrations.AddField(
            model_name='hardware',
            name='warranty',
            field=models.IntegerField(default=0),
        ),
    ]
