# Generated by Django 4.2.1 on 2023-06-09 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0002_hardware_buy_date_hardware_allotment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Softwares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('software_name', models.CharField(max_length=50)),
            ],
        ),
    ]
