# Generated by Django 4.2.1 on 2023-06-09 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0004_rename_asset_id_hardware_asset_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwares',
            name='price',
            field=models.CharField(default=0, max_length=15),
        ),
    ]
