# Generated by Django 4.2.1 on 2023-06-10 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0005_softwares_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Softwares',
        ),
    ]
