# Generated by Django 4.2.1 on 2023-06-10 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0007_hardware_buy_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hardware',
            old_name='Buy_Date',
            new_name='buy_date',
        ),
    ]
