# Generated by Django 4.2.1 on 2023-06-15 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0004_remove_software_software_alter_software_validity'),
        ('hardware', '0008_rename_buy_date_hardware_buy_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hardware',
            name='location',
        ),
        migrations.RemoveField(
            model_name='hardware',
            name='softwares',
        ),
        migrations.AddField(
            model_name='hardware',
            name='softwares',
            field=models.ManyToManyField(to='software.software'),
        ),
    ]
