# Generated by Django 4.2.1 on 2023-06-14 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_employees_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
