# Generated by Django 4.2.1 on 2023-06-15 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0008_rename_buy_date_hardware_buy_date'),
        ('Employee', '0003_employees_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='hardware',
            field=models.ManyToManyField(to='hardware.hardware'),
        ),
    ]
